# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: docs:build
      run: |
        yarn install
        yarn docs:build
        
    - name: docs:publish
      run: |
        cd docs/.vuepress/dist
        git init
        git config --global user.email "maya0301@naver.com"
        git config --global user.name "h2y"
        git remote add origin git@github.com:h2ys:&{{secrets.PAGES_TOKEN}}/h2ys.github.io.git
        git checkout -b pages
        git add -A
        git commit -m 'deploy'
        git push -u origin pages
